### ISSUE TITLE
Library proposal: drupol/phptree ?

### ISSUE THREAD

**Issue by drupol** [ircmaxell/php-ast-visualizer#2]
Hi Anthony,

I just saw your new package, if you're interested, you can use [drupol/phptree](https://github.com/drupol/phptree).
It's a library that handles trees. It has importers and exporters and you might be interested in.

Here's a very basic example that print a graph in SVG: https://gist.github.com/drupol/e6bae31dcd00989268818cf83f6e4ede

**Comment by ircmaxell** [comment]
Well, we're coming from https://github.com/nikic/PHP-Parser so it's already in a tree form. I don't know that it makes sense translating tree structures. Does it?

**Comment by drupol** [comment]
Ok I didn't know that.

However, converting from a tree form into a tree structure (in phptree) would be super easy, then thanks to the Graph exporter, you can export your graph in many formats (Text, GraphViz... etc etc)

I wrote a bit about phptree here: https://not-a-number.io/2018/phptree-a-fast-tree-implementation

Let me know what you think!

**Comment by drupol** [comment]
It's been almost one year! I didn't know this issue was still open :-)

Today I pushed [a new nikic/php-parser importer](https://github.com/loophp/phptree/commit/eeded2730683b2f60a4370628d4a273fdfc12ce2) in "loophp/phptree".

It's now super easy to import an AST into it and play with it.

Here's [a simple example](https://gist.github.com/drupol/11a0e396722a80a72e674d2cb6f22659), the resulting graph is in the comment.

However, thanks to the [Apply](https://github.com/loophp/phptree/blob/master/src/Modifier/Apply.php) and [Filter](https://github.com/loophp/phptree/blob/master/src/Modifier/Filter.php) modifiers, it's possible to alter the tree.

Here's [a more complex example](https://gist.github.com/drupol/ec439d82cb910768193bd82762a5bb48), the resulting graph is in the comment.
